### PR TITLE
Add numeric sort

### PR DESCRIPTION
**Pull request by r-barnes**
Adds the ability to sort the table numerically by a given column in both ascending and descending order.

### CODE REVIEW

**Comment by firecat53** [comment]
Thanks! Please make sure all tests pass. They currently fail most likely because tabview crashes when it hits a non-numeric value in the column. Also, please remove debugging code (the `eprint` statements).

**Comment by r-barnes** [comment]
Okay, that should fix the non-numeric values issue in a reasonable fashion. The debugging code is also removed.

I am not sure how to appropriately update the tests.

**Comment by firecat53** [comment]
FYI, just a few changes I made:

- used the lower case with underscores for the function. Camel Case I use for class names.
- moved the float_string_key method into the class. Probably should be an outside function like you had it, but I was trying to keep everything in a consistent location.
- Added integration test for the '1' and '!'

**Comment by r-barnes** [comment]
Thanks so much.

I wasn't sure where to put `float_string_key`, so I'd left it as an outside function in hopes that this would make moving it to an appropriate location easier. Having it as a "private" member of the class seems a good place.

**Comment by firecat53** [comment]
FYI, I had to change the bindings for numeric sort, as the '1' key took away the ability to specify a column width with the 'c' command. Changed to '#' and '@' (for reverse).

**Pull request merged**
