### PR TITLE
@Interrogator pandas

### PR DESCRIPTION
**Pull request by firecat53**
I merged in @interrogator's tabview master branch into interrogator-panda so we can hack on it and see where it goes (per discussion in #116).

### CODE REVIEW

**Comment by interrogator** [comment]
Great! I'll try to work off this from now on. If anybody has any questions about what I've done, let me know.

To sum up (tested only on Pandas data):

* Keyword argument `align_right` for the `view()` method
* Put a vertical line between index and data
* Moved horizontal line between column names and data
* Bold for index to differentiate from data
* Index is persistent if you scroll horizontally
* Index name shows up in the top left status bit
* Support for MultiIndex (only on Y axis so far)
  * Number of levels auto-detected
  * Sparse display by default
  * Sorting etc by any level works well
* Used Python methods for string padding (e.g. `str.ljust()`), which removed a lot of padding code. This may have changed truncation behaviour a little. Also, the East Asian character width thing might be lost. I don't know anything about it.

Many of these could be easily made configurable, I'm happy to do it on request.

My roadmap would probably include:

* Seeing if the data model could be optimised
* Some key bindings to do Pandas statistical operations on the data (make abs frequencies into rel, for example)
* Use `pandas` for reading and manipulating all data

This last point is a controversial one, since some people might not want a Pandas dependency. But, using `pandas.read_csv()` for example, would really simplify things. I'd like to hear what people think about it!

**Comment by scls19fr** [comment]
Travis build seems broken... maybe you should run CI again.

You can probably also in `.travis.yml` replace

      - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
        else
          wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
        fi

by

      - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi

**Comment by wavexx** [comment]
On Sun, Nov 27 2016, Daniel wrote:
> My roadmap would probably include:
>
> * Seeing if the data model could be optimised
> * Some key bindings to do Pandas statistical operations on the data (make abs frequencies into rel, for example)
> * Use `pandas` for reading and manipulating all data
>
> This last point is a controversial one, since some people might not
> want a Pandas dependency. But, using `pandas.read_csv()` for example,
> would really simplify things. I'd like to hear what people think about
> it!

I'd hate to have pandas as a strict dependency. I'm using tabview in
small boxes to preview tabular files, and there's only the core python
install there.

Also note that pd.read_csv() is much more brittle than you'd think.
It's also not really faster, unless you read into a frame directly.

**Comment by firecat53** [comment]
I agree with @wavexx .... my goal was initially for a simple, lightweight CSV viewer with zero extra dependencies. Pandas/Numpy/Excel support is great but they should be able to be added as 'Adaptors' (coining @wavexx's usage in the 'pandas' branch).

@interrogator, I actually made one change (besides some PEP stuff) in the merge to remove the pandas dependency pulled in by the get_index_depth function. However, my quick fix removes any multi-index support without having pandas installed. I'm thinking that's probably a reasonable trade-off. Thought?

@wavexx, without having dug in too deep myself, is this branch compatible (or fairly easily merged) with the work you did with the adaptor implementation? And do you have the time to create a 'tabviewer' Github organization so we can start moving development that direction (tabview-common, curses, gtabviewer, etc)?

Thanks all!

**Comment by interrogator** [comment]
OK, so it seems that deeply integrating Pandas is a no-no. Fair enough. @firecat53, your fix for `get_index_depth` is exactly right. There somewhere we could put in that feature request for a `freeze` kwarg (#66), too. Would only take a minute to do, though I haven't tested what happens if the `index_depth` is zero yet.

Basically, I'm only using tabview for work with Pandas data, so whatever else I'm writing will target Pandas stuff. I can at least try to make sure that I everything else still works with other formats, however, and some things will work without extra effort (like align left/right). I love the tool, but don't think I'll have much time for developing on data formats I'm not really using...

**Pull request closed without merging**
